# Generated by Django 5.2.6 on 2025-10-01 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_delete_order'),
        ('electric_products', '0002_faq_review_service_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electric_products.service_installation'),
        ),
    ]
