# Generated by Django 5.2.6 on 2025-10-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_products', '0002_faq_review_service_installation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='service_name',
        ),
        migrations.AddField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='electric_products.service_installation'),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='electric_products.service_installation'),
        ),
    ]
