# Generated by Django 5.2.6 on 2025-09-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('hero_img', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Hero Banner',
                'verbose_name_plural': 'Home Hero Banners',
            },
        ),
    ]
