# Generated by Django 5.2.6 on 2025-09-30 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homeherobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStatsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading text', max_length=255)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='home/stats/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='home/stats/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='home/stats/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='home/stats/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Stats Section',
                'verbose_name_plural': 'Home Stats Sections',
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.homestatssection')),
            ],
        ),
    ]
