# Generated by Django 5.2.6 on 2025-09-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homestatssection_statitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestatssection',
            name='heading',
            field=models.CharField(default='Home Stats', help_text='Main heading text', max_length=255),
        ),
        migrations.AlterField(
            model_name='homestatssection',
            name='title',
            field=models.CharField(help_text='Optional subtitle or section title', max_length=255),
        ),
    ]
