# Generated by Django 5.2.6 on 2025-09-30 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homestatssection_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStepsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Proven Three Step Process', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Steps Section',
                'verbose_name_plural': 'Home Steps Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order (1,2,3...). smaller = earlier')),
                ('number_label', models.CharField(blank=True, help_text="Displayed number (e.g. '1')", max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.homestepssection')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
                'ordering': ['order'],
            },
        ),
    ]
