# Generated by Django 5.2.6 on 2025-09-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homestepssection_stepitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestepssection',
            name='step1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homestepssection',
            name='step1_number',
            field=models.CharField(blank=True, default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='homestepssection',
            name='step1_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homestepssection',
            name='step2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homestepssection',
            name='step2_number',
            field=models.CharField(blank=True, default='2', max_length=10),
        ),
        migrations.AddField(
            model_name='homestepssection',
            name='step2_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homestepssection',
            name='step3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homestepssection',
            name='step3_number',
            field=models.CharField(blank=True, default='3', max_length=10),
        ),
        migrations.AddField(
            model_name='homestepssection',
            name='step3_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='StepItem',
        ),
    ]
