# Generated by Django 5.2.6 on 2025-09-30 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homestepssection_step1_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeReviewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='What Our Happy Customers Are Saying', max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Reviews Section',
                'verbose_name_plural': 'Home Reviews Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order: smaller first')),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('review_text', models.TextField()),
                ('person_image', models.ImageField(blank=True, null=True, upload_to='home/reviews/')),
                ('person_name', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.homereviewssection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
