# Generated by Django 5.2.6 on 2025-09-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homereviewssection_reviewitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homereviewssection',
            name='review1_person_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/reviews/'),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review1_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review1_service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review1_stars',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review1_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review2_person_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/reviews/'),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review2_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review2_service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review2_stars',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review2_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review3_person_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/reviews/'),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review3_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review3_service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review3_stars',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review3_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review4_person_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/reviews/'),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review4_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review4_service',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review4_stars',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='homereviewssection',
            name='review4_text',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ReviewItem',
        ),
    ]
