# Generated by Django 5.2.6 on 2025-09-30 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homereviewssection_review1_person_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review1_person_image',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review1_person_name',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review1_service',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review1_stars',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review1_text',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review2_person_image',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review2_person_name',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review2_service',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review2_stars',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review2_text',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review3_person_image',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review3_person_name',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review3_service',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review3_stars',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review3_text',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review4_person_image',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review4_person_name',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review4_service',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review4_stars',
        ),
        migrations.RemoveField(
            model_name='homereviewssection',
            name='review4_text',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField(blank=True)),
                ('person_image', models.ImageField(blank=True, null=True, upload_to='home/reviews/')),
                ('person_name', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(blank=True, max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.homereviewssection')),
            ],
        ),
    ]
