# Generated by Django 5.2.6 on 2025-09-30 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_homereviewssection_review1_person_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBrandsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Trusted Brands We Work With', max_length=255)),
                ('cta_text', models.CharField(default='Get in Touch with Electric Dreams Electrical Today', max_length=255)),
                ('phone_number', models.CharField(default='+91-1234567890', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Brands Section',
                'verbose_name_plural': 'Home Brands Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/brands/')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='core.homebrandssection')),
            ],
        ),
    ]
