# Generated by Django 5.2.6 on 2025-09-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
