# Generated by Django 5.2.6 on 2025-09-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='callback/')),
                ('title', models.CharField(default='Professional Emergency Electrician - Fast & Reliable', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='24-hour Electrician In Electric dreams. Call Our Professional Electricians Now To Get Help Fast')),
                ('stars_count', models.PositiveSmallIntegerField(default=5)),
                ('reviews_text', models.CharField(blank=True, default='Over 215 google reviews', max_length=255)),
                ('call_image', models.ImageField(blank=True, null=True, upload_to='callback/')),
                ('phone_number', models.CharField(blank=True, default='(+91)1234567890', max_length=80)),
                ('feature_cards', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
