# Generated by Django 5.2.6 on 2025-09-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_callbacksection1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Quality Workmanship', max_length=255)),
                ('paragraphs', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, default='+611234567890', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='callback/section2/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
