# Generated by Django 5.2.6 on 2025-09-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_callbacksection2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(default='Get in Touch with Electric Dreams Electrical Today', max_length=255)),
                ('phone', models.CharField(blank=True, default='(+91)1234567890', max_length=80)),
                ('section_title', models.CharField(default='Signs you need an emergency electrician', max_length=255)),
                ('intro', models.TextField(blank=True, default='Many signs indicate when it’s time to call a 24 hour electrician for help with your electrical problems. Here’s a quick list of what to look for:')),
                ('points', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
